; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.41"

; Modules
projects[at_tools][version] = "1.x-dev"

projects[addtoany][version] = "4.9"

projects[advanced_forum][version] = "2.5"

projects[autologout][version] = "4.4"

projects[bean][version] = "1.9"

projects[block_class][version] = "2.1"

projects[block_class_styles][version] = "2.4"

projects[ctools][version] = "1.9"

projects[entity][version] = "1.6"

projects[faq][version] = "1.1"

projects[fivestar][version] = "2.1"

projects[group][version] = "1.0-alpha5"

projects[libraries][version] = "2.2"

projects[phpmailer][version] = "3.x-dev"

projects[panels][version] = "3.5"

projects[jquery_update][version] = "3.0-alpha3"

projects[password_policy][version] = "1.12"

projects[tagclouds][version] = "1.10"

projects[twitter_timeline][version] = "1.x-dev"

projects[views][version] = "3.11"

projects[votingapi][version] = "2.12"

projects[wysiwyg][version] = "2.2"

projects[pathologic][version] = "2.12"

projects[support][version] = "1.0-rc2"

projects[module_filter][version] = "2.0"

projects[captcha][version] = "1.x-dev"

projects[login_redirect][version] = "1.2"

projects[search404][version] = "1.x-dev"

projects[token][version] = "1.6"

projects[flag][version] = "3.7"

projects[imce][version] = "1.9"

projects[imce_wysiwyg][version] = "1.0"

projects[linkit][version] = "3.4"

projects[linkit_picker][version] = "3.0-rc2"

projects[l10n_update][version] = "2.0"

projects[hierarchical_select][version] = "3.0-beta2"

projects[taxonomy_menu][version] = "1.5"

projects[vppr][version] = "1.0"

projects[tfa][version] = "2.0-beta2"

projects[tfa_basic][version] = "1.0-beta2"

projects[legal][version] = "1.5"

projects[variable][version] = "2.5"

projects[i18n][version] = "1.13"

projects[translation_helpers][version] = "1.0"

projects[addressfield][version] = "1.2"

projects[image_captcha_refresh][version] = "1.5"

projects[statsd][version] = "1.0"

projects[syslog_advanced][version] = "1.3"

projects[messaging][version] = "1.0-alpha2"

projects[notifications][version] = "1.0-alpha2"

projects[notifications_forum][version] = "1.0-beta3"

projects[content_approval][version] = "1.1"

projects[fasttoggle][version] = "1.6"

projects[views_bulk_operations][version] = "3.3"

projects[angularjs][version] = "1.4"

projects[security_questions][version] = "2.0"

projects[d3][version] = "1.0-alpha1"

projects[menu_item_visibility][version] = "1.0-beta1"

projects[ultimate_cron][version] = "2.0-rc1"

projects[flood_control][version] = "1.0"

projects[acl][version] = "1.1"

projects[chain_menu_access][version] = "2.0"

projects[forum_access][version] = "1.2"

projects[follow][version] = "2.0-alpha1"

projects[search_autocomplete][version] = "4.7"

projects[markdown][version] = "1.2"

projects[httprl][version] = "1.14"

projects[advagg][version] = "2.16"

projects[slick][version] = "2.0-rc2"

projects[slick_views][version] = "2.0-rc2"

projects[slick_extras][version] = "2.0-beta3"

projects[profanity][version] = "1.x-dev"

projects[seckit][version] = "1.9"

projects[restrict_by_ip][version] = "3.1"

; Themes
projects[adaptivetheme][version] = "3.2"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ibm_apim_theme][download][type] = ""
projects[ibm_apim_theme][download][url] = ""
projects[ibm_apim_theme][type] = "theme"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ibm_apim][download][type] = ""
projects[ibm_apim][download][url] = ""
projects[ibm_apim][type] = "module"

projects[bannerblock][download][type] = ""
projects[bannerblock][download][url] = ""
projects[bannerblock][type] = "module"

projects[forum_approval][download][type] = ""
projects[forum_approval][download][url] = ""
projects[forum_approval][type] = "module"

projects[clone][download][type] = ""
projects[clone][download][url] = ""
projects[clone][type] = "module"

projects[front_page][download][type] = ""
projects[front_page][download][url] = ""
projects[front_page][type] = "module"