<?php

/**
 * IBM API Management Integration
 *
 * Adds the Application node content type to Drupal for representing Applications from IBM APIM
 */

/**
 * Implements hook_node_info().
 */
function plan_node_info() {
  return array(
    'plan' => array(
      'name' => t('Plan'),
      'base' => 'plan',
      'description' => t('A Plan in IBM API Management')));
}

/**
 * Implements hook_help().
 */
function plan_help($path, $arg) {
  switch ($path) {
    case 'admin/help#plan' :
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t("The plan module provides a new custom node type for use with IBM API Management.") . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Select a plan') . '</dt>';
      $output .= '<dd>' . t("This module enables the user to see the different plans available in IBM API Management for a given API, showing the details and any rate limiting policy included in them.") . '</dd>';
      $output .= '<dt>' . t('Subscribe to a plan') . '</dt>';
      $output .= '<dd>' . t("Using this module it is possible for a user to subscribe an application to a plan in IBM API Management.") . '</dd>';
      $output .= '</dl>';
      return $output;
  }
}

/**
 * Implements hook_form().
 */
function plan_form($node, $form_state) {
  return node_content_form($node, $form_state);
}

/**
 * Implements hook_view().
 */
function plan_view($node, $view_mode) {
  return $node;
}

/**
 * Implements hook_node_view().
 */
function plan_node_view($node, $view_mode) {
}

/**
 * Implements hook_menu().
 */
function plan_menu() {
  $items = array();
  $items['plan'] = array(
    'title' => t('Plans'),
    'page callback' => 'plan_collection_callback',
    'menu_name' => 'main-menu',
    'weight' => 15,
    'description' => t('Pricing plans'),
    'access callback' => 'user_is_logged_in');
  $items['plan/subscribe/%/%'] = array(
    'title' => t('Subscribe'),
    'type' => MENU_CALLBACK,
    'page callback' => 'plan_subscribeapp_callback',
    'page arguments' => array(2, 3),
    'access callback' => 'user_is_logged_in');
  return $items;
}

/**
 * Implements hook_node_access().
 * This is checking if the specified plan is returned from apim, if not it blocks access.
 */
function plan_access($node, $op, $account) {
  $type = is_string($node) ? $node : $node->type;
  $planfound = FALSE;
  $plans = plan_list_contents();
  if ($plans) {
    foreach ($plans as $plan) {
      if (isset($node->plan_apiid) && $plan['id'] == $node->plan_apiid[$node->language][0]['value']) {
        $planfound = TRUE;
      }
    }
  }
  if ($planfound == TRUE) {
    return NODE_ACCESS_ALLOW;
  }
  else {
    return NODE_ACCESS_DENY;
  }
}

/**
 * Implements hook_preprocess_node().
 */
function plan_preprocess_node(&$variables) {
  if ($variables['node']->type == 'plan' && $variables['view_mode'] == 'teaser') {
    $variables['theme_hook_suggestions'][] = 'node__plan__teaser';
  }
  if ($variables['node']->type == 'plan' && $variables['view_mode'] == 'search_result') {
    $variables['theme_hook_suggestions'][] = 'node__plan__search_result';
  }
  if ($variables['node']->type == 'plan') {
    $variables['titlelink'] = t('<span class="apimTitle"> <a href="!link">!title</a> </span>', array(
      '!title' => $variables['title'],
      '!link' => url("plan/" . $variables['plan_apiid'][0]['value'] . "/" . $variables['plan_version'][0]['value'])));
    if ($variables['view_mode'] == 'full') {
      $details = plan_details_contents($variables['plan_apiid'][0]['value'], $variables['plan_version'][0]['value']);
      $variables['apis'] = $details['apis'];
    }
  }
}

/**
 * Implements hook_preprocess_search_result
 *
 * @param type $variables
 */
function plan_preprocess_search_result(&$variables) {
  $node = $variables['result']['node'];
  if ($node->nid && $node->type == 'plan') { // if the result is a plan node we can load the teaser
    $variables['teaser'] = node_view($node, 'teaser');
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 * Adds our custom submit handler
 */
function plan_form_comment_form_alter(&$form, &$form_state) {
  // Add a custom submit handler to act when the form submits.
  $form['#submit'][] = 'plan_custom_comment_submit_handler';
}

/**
 * Custom submit handler for the comment form.
 * This is to redirect users back to our custom path after posting a comment
 * e.g. to plan/xxx instead of node/nid
 */
function plan_custom_comment_submit_handler($form, &$form_state) {
  // Redirect the user after submission
  $nid = arg(2);
  if (isset($nid)) {
    $nodes = node_load_multiple(array($nid));
    if (is_array($nodes)) {
      reset($nodes);
      $first_key = key($nodes);
      if ($first_key) {
        $node = $nodes[$first_key];
        if (isset($node) && $node->type == 'plan') {
          $form_state['redirect'] = 'plan/' . $node->plan_apiid[$node->language][0]['value'] . '/' . $node->plan_version[$node->language][0]['value'];
        }
      }
    }
  }
}

/**
 * Callback to display a form for subscribing an app to a plan.
 */
function plan_subscribeapp_callback($planid = NULL, $planversion = NULL) {
  $markup = '';
  ctools_include('ajax');
  ctools_include('modal');
  ctools_modal_add_js();
  $app_form = drupal_get_form('plan_subscribeapp_modal_form', $planid, $planversion);
  $markup .= drupal_render($app_form);
  return array('#markup' => $markup);
}

/**
 * Form for subscribing an app to a plan.
 */
function plan_subscribeapp_modal_form($form, &$form_state, $planId, $planVersion) {
  $apps = application_list_contents();
  $options = array();
  if ($apps) {
    foreach ($apps as $app) {
      $options[$app['id']] = $app['name'];
    }
  }

  // $active = array(0 => t('Closed'), 1 => t('Active'));

  $form['planId'] = array('#type' => 'hidden', '#value' => $planId);
  $form['planVersion'] = array('#type' => 'hidden', '#value' => $planVersion);
  $form['orgId'] = array(
    '#type' => 'hidden',
    '#value' => ibm_apim_get_current_developer_org()['id']);
  $form['host'] = array(
    '#type' => 'hidden',
    '#value' => variable_get('ibm_apim_host'));

  $form['app'] = array(
    '#type' => 'radios',
    '#title' => t('Application'),
    '#options' => $options,
    '#description' => t('Select an application to sign up to this plan'));
  $form["#submit"][] = "plan_subscribeapp_modal_form_submit";

  $form['submit'] = array('#type' => 'submit', '#value' => t('Save'));

  return $form;
}

/**
 * Validate handler for subscribing an app to a plan.
 */
function plan_subscribeapp_modal_form_validate($form, &$form_state) {
}

/**
 * Submit handler for subscribing an app to a plan.
 */
function plan_subscribeapp_modal_form_submit($form, &$form_state) {
  ctools_include('ajax');
  ctools_include('modal');

  $appId = $form_state['values']['app'];
  $planId = $form_state['values']['planId'];
  $planVersion = $form_state['values']['planVersion'];
  $orgId = $form_state['values']['orgId'];
  $host = $form_state['values']['host'];
  if (isset($orgId)) {
    $developer_org_url = '/orgs/' . $orgId;
  }
  else {
    $developer_org_url = '';
  }

  $url = '/v1/portal/' . $developer_org_url . '/apps/' . $appId . '/subscriptions';
  $planurl = 'https://' . $host . '/v1/portal/' . $developer_org_url . '/plans/' . $planId . '/v' . $planVersion;
  $data = '{"planURL":" ' . $planurl . '"}';

  $result = _ibm_apim_post($url, $data);
  // dismiss the popup
  $form_state['plan_subscribeapp'][] = ctools_modal_command_dismiss();
  // redirect to the application page
  drupal_goto("application/" . $appId, array());
}

/**
 * Menu callback;
 * if a specific plan has been requested will display that as full viewmode,
 * else it will show teaser viewmode for all available plans
 */
function plan_collection_callback($planid = NULL, $planversion = NULL) {
  global $user;
  $build = array();
  $host = variable_get('ibm_apim_host');
  if (empty($host)) {
    drupal_set_message(t('IBM APIM Module is not correctly configured. Specify a valid hostname and try again.'), 'error');
    return;
  }

  if ($planid == NULL || $planversion == NULL) {
    $nodes = array();

    $query = db_select('node', 'n')->extend('PagerDefault');
    $nids = $query->fields('n', array('nid'))->condition('type', 'plan')->condition('status', 1)->limit(variable_get('default_nodes_main', 100))->addTag('node_access')->execute()->fetchCol();
    if (!empty($nids)) {
      $nodes = node_load_multiple($nids);
    }

    $plans = plan_list_contents();
    if ($plans) {
      foreach ($plans as $plan) {
        $planfound = FALSE;
        if ($nodes) {
          foreach ($nodes as $node) {
            if (isset($node->plan_apiid) && isset($node->plan_version) && $plan['id'] == $node->plan_apiid[$node->language][0]['value'] && $plan['version'] == $node->plan_version[$node->language][0]['value']) {
              $planfound = TRUE;
              _plan_updateExistingPlanNode($node, $plan);
            }
          }
        }
        if ($planfound == FALSE) {
          _plan_createNewPlanNode($plan);
        }
      }
    }
    // rerun query now we've created entries for any new Plans we found
    $nids = $query->fields('n', array('nid'))->condition('type', 'plan')->condition('status', 1)->limit(variable_get('default_nodes_main', 100))->addTag('node_access')->execute()->fetchCol();
    $finalnids = array();

    if (!empty($nids)) {
      // now remove the nodes that weren't in our list of Plans
      if ($plans) {
        $nodes = node_load_multiple($nids);
        if ($nodes) {
          foreach ($nodes as $node) {
            foreach ($plans as $plan) {
              if (isset($node->plan_apiid) && isset($node->plan_version) && $plan['id'] == $node->plan_apiid[$node->language][0]['value'] && $plan['version'] == $node->plan_version[$node->language][0]['value']) {
                array_push($finalnids, $node->nid);
              }
            }
          }
        }
      }

      $finalnodes = node_load_multiple($finalnids);
      if ($finalnodes) {
        $build = array(
          'nodes' => node_view_multiple($finalnodes),
          'pager' => array('#markup' => theme('pager')));
      }
      else {
        drupal_set_message(t('No plans have been found.'), 'warning');
      }
    }
    else {
      drupal_set_message(t('No plans have been found.'), 'warning');
    }
  }
  else {
    // specific plan
    $plan = plan_details_contents($planid, $planversion);
    if (isset($plan)) {
      $query = new EntityFieldQuery();
      $query->entityCondition('entity_type', 'node')->entityCondition('bundle', 'plan')->fieldCondition('plan_apiid', 'value', $planid)->fieldCondition('plan_version', 'value', $planversion);

      $results = $query->execute();

      if (isset($results['node'])) {
        $node = node_load(array_keys($results['node'])[0]);
        _plan_updateExistingPlanNode($node, $plan);
        $node = node_load($node->nid);
        // load it again now we've updated it
        // $build = node_page_view($node);
        $build = node_page_view($node, 'full', NULL);
        $more = module_invoke_all('node_view', $node, 'full', NULL);
        // Only append comments when we are building a node on its own node detail
        // page. Hardcoded here as comment module will do a node_is_page check which we wouldnt pass
        // since path is /plan not /node
        $comments_enabled = variable_get('comment_plan', 1);
        if ($node->comment && empty($node->in_preview) && ($comments_enabled == 1)) {
          $node->content['comments'] = comment_node_page_additions($node);
        }
        $build_all = array_merge($build, $more);
        return $build_all;
      }
      else {
        // no existing node for this Plan so create one
        $nid = _plan_createNewPlanNode($plan);
        $node = node_load($nid);

        $build = node_page_view($node, 'full', NULL);
        $more = module_invoke_all('node_view', $node, 'full', NULL);
        // Only append comments when we are building a node on its own node detail
        // page. Hardcoded here as comment module will do a node_is_page check which we wouldnt pass
        // since path is /plan not /node
        $comments_enabled = variable_get('comment_plan', 1);
        if ($node->comment && empty($node->in_preview) && ($comments_enabled == 1)) {
          $node->content['comments'] = comment_node_page_additions($node);
        }
        $build_all = array_merge($build, $more);
        return $build_all;
      }
    }
    else {
      drupal_set_message(t('The specified Plan could not be found.'), 'error');
    }
  }
  return $build;
}

/**
 * Create a new Plan node
 * Used to create the new placeholder nodes for any new Plans returned by APIm
 */
function _plan_createNewPlanNode($plan) {
  global $user;
  $node = new stdClass();
  $node->title = $plan['name'];
  $node->type = "plan";
  node_object_prepare($node); // Sets some defaults. Invokes hook_prepare() and hook_node_prepare().
  $node->language = LANGUAGE_NONE;
  $node->uid = $user->uid;
  $node->status = 1;
  $node->promote = 0;
  $node->comment = 2;

  $node->plan_apiid[$node->language][] = array(
    'value' => $plan['id'],
    'format' => 'plain_text');
  $node->plan_version[$node->language][] = array(
    'value' => $plan['version'],
    'format' => 'plain_text');
  $node->plan_description[$node->language][] = array(
    'value' => $plan['description'],
    'format' => 'plain_text');
  $node->plan_displayname[$node->language][] = array(
    'value' => $plan['displayName'],
    'format' => 'plain_text');
  $node->plan_requiresapproval[$node->language][] = array(
    'value' => $plan['requiresApproval'],
    'format' => 'plain_text');
  $node->plan_url[$node->language][] = array(
    'value' => $plan['url'],
    'format' => 'plain_text');
  $node->plan_updated[$node->language][] = array(
    'value' => $plan['updatedAt'],
    'format' => 'plain_text');
  $node = node_submit($node); // Prepare node for saving
  node_save($node);
  return $node->nid;
}

/**
 * Update an existing Plan node
 * Used to update the placeholder node for any new Plan details returned by APIm
 */
function _plan_updateExistingPlanNode($node, $plan) {
  $node->title = $plan['name'];
  $node->plan_apiid[$node->language][0]['value'] = $plan['id'];
  $node->plan_version[$node->language][0]['value'] = $plan['version'];
  $node->plan_description[$node->language][0]['value'] = $plan['description'];
  $node->plan_displayname[$node->language][0]['value'] = $plan['displayName'];
  $node->plan_requiresapproval[$node->language][0]['value'] = $plan['requiresApproval'];
  $node->plan_url[$node->language][0]['value'] = $plan['url'];
  $node->plan_updated[$node->language][0]['value'] = $plan['updatedAt'];
  node_save($node);
}

/**
 * A function to lookup all the plans a user can see and return the basic
 * information for each of them.
 *
 * @return array NULL if an error occurs otherwise an array with data for each
 *         plan found.
 */
function plan_list_contents() {
  $plan_data = NULL;
  $developerOrg = ibm_apim_get_current_developer_org()['id'];
  if (isset($developerOrg)) {
    $url = '/v1/portal/orgs/' . $developerOrg . '/plans';
  }
  else {
    $url = '/v1/portal/plans';
  }
  $result = _ibm_apim_call($url);
  if (isset($result) && isset($result->data)) {
    $plan_data = $result->data;
  }
  return $plan_data;
}

/**
 * A function to retrieve the details for a specified plan
 *
 * @param
 *          string planid
 *          The plan id
 *
 * @param
 *          int planversion
 *          The plan version
 *
 * @return array NULL if an error occurs otherwise an array with data for the plan.
 */
function plan_details_contents($planid = NULL, $planversion = NULL) {
  $plan_data = NULL;
  $developerOrgs = ibm_apim_get_current_developer_org()['id'];

  if (isset($developerOrgs)) {
    $developer_org_url = '/orgs/' . $developerOrgs;
  }
  else {
    $developer_org_url = '';
  }

  $planURL = '/v1/portal' . $developer_org_url . '/plans/' . $planid . '/v' . $planversion;
  $result = _ibm_apim_call($planURL);
  if (isset($result) && isset($result->data)) {
    $plan_data = $result->data;
  }
  return $plan_data;
}
