<?php

/**
 * IBM API Management Integration
 *
 * Adds the Application node content type to Drupal for representing Applications from IBM APIM
 */

/**
 * Implements hook_node_info().
 */
function application_node_info() {
  return array(
    'application' => array(
      'name' => t('Application'),
      'base' => 'application',
      'description' => t('An application in IBM API Management')));
}

/**
 * Implements hook_help().
 */
function application_help($path, $arg) {
  switch ($path) {
    case 'admin/help#application' :
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t("The application module provides a new custom node type for use with IBM API Management.") . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('List applications') . '</dt>';
      $output .= '<dd>' . t("Nodes of this type are used to show the applications registered to the current user.") . '</dd>';
      $output .= '<dt>' . t('Register a new application') . '</dt>';
      $output .= '<dd>' . t("This module will allow the user to register a new application in IBM API Management") . '</dd>';
      $output .= '</dl>';
      return $output;
  }
}

/**
 * Implements hook_form().
 */
function application_form($node, $form_state) {
  return node_content_form($node, $form_state);
}

/**
 * Implements hook_view().
 */
function application_view($node, $view_mode) {
  return $node;
}

/**
 * Implements hook_node_view().
 */
function application_node_view($node, $view_mode) {
}

/**
 * Implements hook_menu().
 */
function application_menu() {
  $items = array();
  $items['application'] = array(
    'title' => t('Apps'),
    'page callback' => 'application_collection_callback',
    'menu_name' => 'main-menu',
    'weight' => 10,
    'description' => t('Your registered apps'),
    'access callback' => 'user_is_logged_in');
  $items['application/new'] = array(
    'title' => t('Register an application'),
    'description' => t('Form to register a new application.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_application_add_application_form'),
    'menu_name' => 'ibm_apim',
    'access callback' => 'user_is_logged_in');
  $items['application/%/edit'] = array(
    'title' => t('Edit an application'),
    'description' => t('Form to edit an application.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_application_edit_application_form', 1),
    'menu_name' => 'ibm_apim',
    'access callback' => 'user_is_logged_in');
  $items['application/%/delete'] = array(
    'title' => t('Delete an application'),
    'description' => t('Form to delete an application.'),
    'page callback' => '_application_delete_application_submit_handler',
    'page arguments' => array(1),
    'menu_name' => 'ibm_apim',
    'access callback' => 'user_is_logged_in');
  $items['application/%/verify'] = array(
    'title' => t('Verify an application secret'),
    'description' => t('Form to verify an application secret.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_application_verify_application_secret_form', 1),
    'menu_name' => 'ibm_apim',
    'access callback' => 'user_is_logged_in');
  $items['application/%/reset-clientid'] = array(
    'title' => t('Reset an application Client ID'),
    'description' => t('Reset an application Client ID.'),
    'page callback' => 'application_reset_application_clientid_submit_handler',
    'page arguments' => array(1),
    'menu_name' => 'ibm_apim',
    'access callback' => 'user_is_logged_in');
  $items['application/%/reset-secret'] = array(
    'title' => t('Reset an application secret'),
    'description' => t('Reset an application secret.'),
    'page callback' => 'application_reset_application_secret_submit_handler',
    'page arguments' => array(1),
    'menu_name' => 'ibm_apim',
    'access callback' => 'user_is_logged_in');
  $items['application/%/upload'] = array(
    'title' => t('Upload an application image'),
    'description' => t('Form to upload an application image.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_application_upload_application_image_form', 1),
    'menu_name' => 'ibm_apim',
    'access callback' => 'user_is_logged_in');
  $items['application/%/removeimage'] = array(
    'title' => t('Remove an application image'),
    'description' => t('Form to remove an application\'s image.'),
    'page callback' => '_application_delete_image_submit_handler',
    'page arguments' => array(1),
    'menu_name' => 'ibm_apim',
    'access callback' => 'user_is_logged_in');
  $items['application/%/unsubscribe/%'] = array(
    'title' => t('Unsubscribe'),
    'type' => MENU_CALLBACK,
    'page callback' => 'application_unsubscribeapp_submit_handler',
    'page arguments' => array(1, 3),
    'access callback' => 'user_is_logged_in');
  $items['application/%/notifysettings'] = array(
    'title' => t('Edit application notification settings'),
    'description' => t('Form to edit application notification settings.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array(
      '_application_update_notification_settings_form',
      1),
    'menu_name' => 'ibm_apim',
    'access callback' => 'user_is_logged_in');
  return $items;
}

/**
 * Implements hook_node_access().
 * This is checking if the specified application is returned from apim, if not it blocks access.
 */
function application_access($node, $op, $account) {
  $type = is_string($node) ? $node : $node->type;
  $appfound = FALSE;
  $apps = application_list_contents();
  if ($apps) {
    foreach ($apps as $app) {
      if (isset($node->application_apiid) && $app['id'] == $node->application_apiid[$node->language][0]['value']) {
        $appfound = TRUE;
      }
    }
    if ($appfound == TRUE) {
      return NODE_ACCESS_ALLOW;
    }
    else {
      return NODE_ACCESS_DENY;
    }
  }
  else {
    return NODE_ACCESS_DENY;
  }
}

/**
 * Implements hook_preprocess_node().
 */
function application_preprocess_node(&$variables) {
  if ($variables['node']->type == 'application' && $variables['view_mode'] == 'teaser') {
    $variables['theme_hook_suggestions'][] = 'node__application__teaser';
  }
  if ($variables['node']->type == 'application' && $variables['view_mode'] == 'search_result') {
    $variables['theme_hook_suggestions'][] = 'node__application__search_result';
  }
  if ($variables['node']->type == 'application') {
    $variables['titlelink'] = '<span class="apimTitle"> <a href="' . url("application/" . $variables['application_apiid'][0]['safe_value']) . '">' . $variables['title'] . '</a> </span>';
    $variables['uploadimagelink'] = '<span class="uploadlink"><a href="' . url("application/" . $variables['application_apiid'][0]['value'] . "/upload") . '">' . t('Upload image') . '<img class="uploadIcon" title="' . t('Upload') . '" src="' . file_create_url(drupal_get_path('module', 'ibm_apim') . '/images/upload.png') . '" height="20" width="20" alt="' . t('Upload application image') . '" /></a> </span>';
    $variables['removeimagelink'] = '<span class="removelink"><a href="' . url("application/" . $variables['application_apiid'][0]['value'] . "/removeimage") . '"><img class="removeIcon" title="' . t('Remove image') . '" src="' . file_create_url(drupal_get_path('module', 'ibm_apim') . '/images/remove.png') . '" height="16" width="16" alt="' . t('Remove application image') . '" /></a> </span>';
    $variables['verifysecretlink'] = ' <a href="' . url("application/" . $variables['application_apiid'][0]['value'] . "/verify") . '">' . t('Verify') . '</a> ';
    $variables['resetclientidlink'] = ' <a href="' . url("application/" . $variables['application_apiid'][0]['value'] . "/reset-clientid") . '">' . t('Reset') . '</a> ';
    $variables['resetsecretlink'] = ' <a href="' . url("application/" . $variables['application_apiid'][0]['value'] . "/reset-secret") . '">' . t('Reset') . '</a> ';
    $variables['notificationsettings_enabledlink'] = ' <a href="' . url("application/" . $variables['application_apiid'][0]['value'] . "/notifysettings") . '"><img title="' . t('Edit notification settings') . '" src="' . file_create_url(drupal_get_path('module', 'ibm_apim') . '/images/notify_16_on.png') . '" height="16" width="16" class="notifcationSettingsIcon" alt="' . t('Edit notification settings') . '" /></a> ';
    $variables['notificationsettings_disabledlink'] = ' <a href="' . url("application/" . $variables['application_apiid'][0]['value'] . "/notifysettings") . '"><img title="' . t('Edit notification settings') . '" src="' . file_create_url(drupal_get_path('module', 'ibm_apim') . '/images/notify_16_up.png') . '" height="16" width="16" class="notifcationSettingsIcon" alt="' . t('Edit notification settings') . '" /></a> ';
    $variables['editlink'] = ' <a href="' . url("application/" . $variables['application_apiid'][0]['value'] . "/edit") . '"><img title="' . t('Edit') . '" src="' . file_create_url(drupal_get_path('module', 'ibm_apim') . '/images/edit_button.png') . '" height="20" width="20" alt="' . t('Edit') . '" /></a> ';
    $variables['deletelink'] = ' <a href="' . url("application/" . $variables['application_apiid'][0]['value'] . "/delete") . '"><img title="' . t('Delete') . '" src="' . file_create_url(drupal_get_path('module', 'ibm_apim') . '/images/delete_button.png') . '" height="20" width="20" alt="' . t('Delete') . '" /></a> ';
    if ($variables['application_imageurl'][0]['value'] != NULL) {
      $image_data = ibm_apim_raw_data('/v1/portal/orgs/' . ibm_apim_get_current_developer_org()['id'] . '/apps/' . $variables['application_apiid'][0]['value'] . '/image');
      if ($image_data == NULL || $image_data->code == '204') {
        $variables['appimagedata'] = '';
      }
      else {
        $mime_type = $image_data->headers['Content-Type'];
        $image = 'data:' . $mime_type . ';base64,' . base64_encode($image_data->data);
        $variables['appimagedata'] = $image;
      }
    }
    else {
      $variables['appimagedata'] = '';
    }
    if ($variables['view_mode'] == 'full') {
      $details = application_details_contents($variables['application_apiid'][0]['value']);
      $variables['subscriptions'] = $details['subscriptions'];
      $variables['appclientid'] = $details['clientID'];
      $variables['notificationsettings'] = ibm_apim_get_app_notification_settings($variables['application_apiid'][0]['safe_value']);
    }
  }
}

/**
 * Implements hook_preprocess_search_result
 *
 * @param type $variables
 */
function application_preprocess_search_result(&$variables) {
  $node = $variables['result']['node'];
  if ($node->nid && $node->type == 'application') { // if the result is an application node we can load the teaser
    $variables['teaser'] = node_view($node, 'teaser');
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 * Adds our custom submit handler
 */
function application_form_comment_form_alter(&$form, &$form_state) {
  // Add a custom submit handler to act when the form submits.
  $form['#submit'][] = 'application_custom_comment_submit_handler';
}

/**
 * Custom submit handler for the comment form.
 * This is to redirect users back to our custom path after posting a comment
 * e.g. to application/xxx instead of node/nid
 */
function application_custom_comment_submit_handler($form, &$form_state) {
  // Redirect the user after submission
  $nid = arg(2);
  if (isset($nid)) {
    $nodes = node_load_multiple(array($nid));
    if (is_array($nodes)) {
      reset($nodes);
      $first_key = key($nodes);
      if ($first_key) {
        $node = $nodes[$first_key];
        if (isset($node) && $node->type == 'application') {
          $form_state['redirect'] = 'application/' . $node->application_apiid[$node->language][0]['value'];
        }
      }
    }
  }
}

/**
 * Menu callback;
 * if a specific app has been requested will display that as full viewmode,
 * else it will show teaser viewmode for all available applications
 */
function application_collection_callback($appId = NULL) {
  global $user;
  $build = array();
  $host = variable_get('ibm_apim_host');
  if (empty($host)) {
    drupal_set_message(t('IBM APIM Module is not correctly configured. Specify a valid hostname and try again.'), 'error');
    return;
  }

  // not after a specific app
  if ($appId == NULL) {
    $nodes = array();

    $query = db_select('node', 'n')->extend('PagerDefault');
    $nids = $query->fields('n', array('nid'))->condition('type', 'application')->condition('status', 1)->limit(variable_get('default_nodes_main', 100))->addTag('node_access')->execute()->fetchCol();
    if (!empty($nids)) {
      $nodes = node_load_multiple($nids);
    }

    $apps = application_list_contents();
    if (!empty($apps)) {
      foreach ($apps as $app) {
        $appfound = FALSE;
        if ($nodes) {
          foreach ($nodes as $node) {
            if (isset($node->application_apiid) && $app['id'] == $node->application_apiid[$node->language][0]['value']) {
              $appfound = TRUE;
              _application_updateExistingApplicationNode($node, $app);
            }
          }
        }
        if ($appfound == FALSE) {
          _application_createNewApplicationNode($app);
        }
      }
    }
    // rerun query now we've created entries for any new Applications we found
    $nids = $query->fields('n', array('nid'))->condition('type', 'application')->condition('status', 1)->limit(variable_get('default_nodes_main', 100))->addTag('node_access')->execute()->fetchCol();

    if (!empty($nids)) {
      $nodes = node_load_multiple($nids);
      $finalnids = array();
      // now remove the nodes that weren't in our list of Apps
      if ($apps) {
        $nodes = node_load_multiple($nids);
        if ($nodes) {
          foreach ($nodes as $node) {
            foreach ($apps as $app) {
              if (isset($node->application_apiid) && $app['id'] == $node->application_apiid[$node->language][0]['value']) {
                array_push($finalnids, $node->nid);
              }
            }
          }
        }
      }
      $finalnodes = node_load_multiple($finalnids);
      if ($finalnodes) {
        $build = array(
          'nodes' => node_view_multiple($finalnodes),
          'pager' => array('#markup' => theme('pager')));
      }
      else {
        drupal_set_message(t('No applications have been found.'), 'warning');
      }
    }
    else {
      drupal_set_message(t('No applications have been found.'), 'warning');
    }
  }
  else {
    // specific app
    $app = application_details_contents($appId);
    if (isset($app)) {
      $query = new EntityFieldQuery();
      $query->entityCondition('entity_type', 'node')->entityCondition('bundle', 'application')->fieldCondition('application_apiid', 'value', $appId);

      $results = $query->execute();

      if (isset($results['node'])) {
        $node = node_load(array_keys($results['node'])[0]);
        _application_updateExistingApplicationNode($node, $app);
        $node = node_load($node->nid);
        // load it again now we've updated it
        // $build = node_page_view($node);
        $build = node_page_view($node, 'full', NULL);
        $more = module_invoke_all('node_view', $node, 'full', NULL);
        // Only append comments when we are building a node on its own node detail
        // page. Hardcoded here as comment module will do a node_is_page check which we wouldnt pass
        // since path is /application not /node
        $comments_enabled = variable_get('comment_application', 1);
        if ($node->comment && empty($node->in_preview) && ($comments_enabled == 1)) {
          $node->content['comments'] = comment_node_page_additions($node);
        }
        $build_all = array_merge($build, $more);
        return $build_all;
      }
      else {
        // no existing node for this Application so create one
        $nid = _application_createNewApplicationNode($app);
        $node = node_load($nid);

        $build = node_page_view($node, 'full', NULL);
        $more = module_invoke_all('node_view', $node, 'full', NULL);
        // Only append comments when we are building a node on its own node detail
        // page. Hardcoded here as comment module will do a node_is_page check which we wouldnt pass
        // since path is /application not /node
        $comments_enabled = variable_get('comment_application', 1);
        if ($node->comment && empty($node->in_preview) && ($comments_enabled == 1)) {
          $node->content['comments'] = comment_node_page_additions($node);
        }
        $build_all = array_merge($build, $more);
        return $build_all;
      }
    }
    else {
      drupal_set_message(t('The specified application could not be found.'), 'error');
    }
  }

  return $build;
}

/**
 * Create a new Application node
 * Used to create the new placeholder nodes for any new Applications returned by APIm
 */
function _application_createNewApplicationNode($app) {
  global $user;
  $node = new stdClass();
  $node->title = $app['name'];
  $node->type = "application";
  node_object_prepare($node); // Sets some defaults. Invokes hook_prepare() and hook_node_prepare().
  $node->language = LANGUAGE_NONE;
  $node->uid = $user->uid;
  $node->status = 1;
  $node->promote = 0;
  $node->comment = 2;

  $node->application_apiid[$node->language][] = array(
    'value' => $app['id'],
    'format' => 'plain_text');
  $node->application_description[$node->language][] = array(
    'value' => $app['description'],
    'format' => 'plain_text');
  $node->application_orgid[$node->language][] = array(
    'value' => $app['orgID'],
    'format' => 'plain_text');
  $node->application_public[$node->language][] = array(
    'value' => $app['public'],
    'format' => 'plain_text');
  $node->application_credentialsurl[$node->language][] = array(
    'value' => $app['credentialsURL'],
    'format' => 'plain_text');
  $node->application_enabled[$node->language][] = array(
    'value' => $app['enabled'],
    'format' => 'plain_text');
  $node->application_imageurl[$node->language][] = array(
    'value' => $app['imageURL'],
    'format' => 'plain_text');
  $node->application_oauthredirecturi[$node->language][] = array(
    'value' => $app['oauthRedirectURI'],
    'format' => 'plain_text');
  $node->application_url[$node->language][] = array(
    'value' => $app['url'],
    'format' => 'plain_text');
  $node->application_updated[$node->language][] = array(
    'value' => $app['updatedAt'],
    'format' => 'plain_text');
  $node = node_submit($node); // Prepare node for saving
  node_save($node);
  return $node->nid;
}

/**
 * Update an existing Application node
 * Used to update the placeholder node for any new Application details returned by APIm
 */
function _application_updateExistingApplicationNode($node, $app) {
  $node->title = $app['name'];
  $node->application_apiid[$node->language][0]['value'] = $app['id'];
  $node->application_description[$node->language][0]['value'] = $app['description'];
  $node->application_orgid[$node->language][0]['value'] = $app['orgID'];
  $node->application_public[$node->language][0]['value'] = $app['public'];
  $node->application_credentialsurl[$node->language][0]['value'] = $app['credentialsURL'];
  $node->application_enabled[$node->language][0]['value'] = $app['enabled'];
  $node->application_imageurl[$node->language][0]['value'] = $app['imageURL'];
  $node->application_oauthredirecturi[$node->language][0]['value'] = $app['oauthRedirectURI'];
  $node->application_url[$node->language][0]['value'] = $app['url'];
  $node->application_updated[$node->language][0]['value'] = $app['updatedAt'];
  node_save($node);
}

/**
 * A function to retrieve the list of applications to which a user has access.
 *
 * @return array NULL if an error occurs otherwise an array with data for each application.
 */
function application_list_contents() {
  $returnValue = NULL;
  $org = ibm_apim_get_current_developer_org();
  if (isset($org)) {
    $result = _ibm_apim_call($org['url'] . '/apps');
    if (isset($result) && isset($result->data)) {
      $app_data = $result->data;
      foreach ($app_data as $app_details) {
        if (is_null($returnValue)) {
          $returnValue = array();
        }
        $temparry = array();
        $temparray['orgID'] = $app_details['orgID'];
        $temparray['name'] = $app_details['name'];
        $temparray['id'] = $app_details['id'];
        $temparray['description'] = $app_details['description'];
        $temparray['clientID'] = $app_details['credentials']['clientID'];
        $temparray['clientSecret'] = $app_details['credentials']['clientSecret'];
        $temparray['credentialsURL'] = $app_details['credentials']['url'];
        $temparray['imageURL'] = $app_details['imageURL'];
        $temparray['public'] = $app_details['public'];
        $temparray['enabled'] = $app_details['enabled'];
        $temparray['updatedAt'] = $app_details['updatedAt'];
        $temparray['oauthRedirectURI'] = $app_details['oauthRedirectURI'];
        $temparray['url'] = $app_details['url'];
        $returnValue[] = $temparray;
      }
    }
  }
  return $returnValue;
}

/**
 * A function to retrieve the details for a specified application and all
 * plans registered with the application
 *
 * @param
 *          string appId
 *          The application id
 *
 * @return array NULL if an error occurs otherwise an array with data for the application
 *         and registered plans.
 */
function application_details_contents($appId) {
  $returnValue = NULL;
  if ($appId == 'new') {
    $returnValue = '';
    return $returnValue;
  }
  $developerOrg = ibm_apim_get_current_developer_org()['id'];
  $url = '/v1/portal/orgs/' . $developerOrg . '/apps';
  $result = _ibm_apim_call($url);
  if (isset($result) && isset($result->data)) {
    $app_result = $result->data;
  }
  $app_data = NULL;
  if (isset($app_result)) {
    foreach ($app_result as $app) {
      if ($app['id'] == $appId) {
        $app_data = $app;
        break;
      }
    }
    if (!isset($app_data)) {
      return NULL;
    }
    $returnValue = array();
    $returnValue['orgID'] = $app_data['orgID'];
    $returnValue['id'] = $app_data['id'];
    $returnValue['name'] = $app_data['name'];
    $returnValue['description'] = $app_data['description'];
    $returnValue['clientID'] = $app_data['credentials']['clientID'];
    $returnValue['clientSecret'] = $app_data['credentials']['clientSecret'];
    $returnValue['credentialsURL'] = $app_data['credentials']['url'];
    $returnValue['imageURL'] = $app_data['imageURL'];
    $returnValue['public'] = $app_data['public'];
    $returnValue['enabled'] = $app_data['enabled'];
    $returnValue['updatedAt'] = $app_data['updatedAt'];
    $returnValue['oauthRedirectURI'] = $app_data['oauthRedirectURI'];
    $returnValue['url'] = $app_data['url'];
    $returnValue['secret_verify_url'] = '/v1/portal/orgs/' . $developerOrg . '/apps/' . $appId . '/credentials/verify-secret';
    $returnValue['secret_reset_url'] = '/v1/portal/orgs/' . $developerOrg . '/apps/' . $appId . '/credentials/reset-secret';
    $image_data = ibm_apim_raw_data('/v1/portal/orgs/' . $developerOrg . '/apps/' . $app_data['id'] . '/image');
    if ($image_data == NULL || $image_data->code == '204') {
      $returnValue['image'] = '';
    }
    else {
      $mime_type = $image_data->headers['Content-Type'];
      $image = 'data:' . $mime_type . ';base64,' . base64_encode($image_data->data);
      $returnValue['image'] = $image;
    }

    $url = '/v1/portal/orgs/' . $developerOrg . '/apps/' . $appId . '/subscriptions';
    $result = _ibm_apim_call($url);
    if (isset($result) && isset($result->data)) {
      $sub_data = $result->data;
    }
    $returnValue['subscriptions'] = array();
    if ($sub_data) {
      foreach ($sub_data as $sub_details) {
        $parts = _application_get_id_and_ver_from_planurl($sub_details['planURL']);
        $temp_array = plan_details_contents($parts['id'], $parts['version']);
        if (isset($temp_array)) {
          $temp_array['approved'] = $sub_details['approved'];
          $temp_array['subId'] = $sub_details['id'];
          $returnValue['subscriptions'][] = $temp_array;
        }
      }
    }
  }
  return $returnValue;
}

/**
 * Submit handler to reset an application client ID
 *
 * @param
 *          string appId
 *          The application ID
 */
function application_reset_application_clientid_submit_handler($appId) {
  $url = '/v1/portal/orgs/' . ibm_apim_get_current_developer_org()['id'] . '/apps/' . $appId . '/credentials/reset';
  $data = '{"clientSecret": false, "clientID": true }';
  $result = ibm_apim_put($url, $data);
  if (isset($result) && $result->code >= 200 && $result->code < 300) {
    drupal_set_message(t('Application Client ID reset: !html_start@label!html_end', array(
      '!html_start' => '<div id="app_secret" class="appClientReset"><input class="toggle-password" id="clientSecret" type="password" readonly value="' . $result->data['clientID'] . '"><div class="passwordToggleContainer"><input type="checkbox" id="show-clientSecret"> <label for="show-clientSecret">',
      '@label' => t('Show Client ID'),
      '!html_end' => '</label></div></div>')));
  }
  drupal_goto('application/' . $appId);
}

/**
 * Submit handler to reset an application client secret
 *
 * @param
 *          string appId
 *          The application ID
 */
function application_reset_application_secret_submit_handler($appId) {
  $url = '/v1/portal/orgs/' . ibm_apim_get_current_developer_org()['id'] . '/apps/' . $appId . '/credentials/reset';
  $data = '{"clientSecret": true, "clientID": false }';
  $result = ibm_apim_put($url, $data);
  if (isset($result) && $result->code >= 200 && $result->code < 300) {
    drupal_set_message(t('Application secret reset: !html_start@label!html_end', array(
      '!html_start' => '<div id="app_secret" class="appSecretReset"><input class="toggle-password" id="clientSecret" type="password" readonly value="' . $result->data['clientSecret'] . '"><div class="passwordToggleContainer"><input type="checkbox" id="show-clientSecret"> <label for="show-clientSecret">',
      '@label' => t('Show Client Secret'),
      '!html_end' => '</label></div></div>')));
  }
  drupal_goto('application/' . $appId);
}

/**
 * Form to upload an image to assign to an application
 *
 * @param
 *          form
 *          The form
 *
 * @param
 *          form_state
 *          The form state
 *
 * @param
 *          string app_id
 *          The application ID
 */
function _application_upload_application_image_form($form, &$form_state, $app_id) {
  $form['app_id'] = array('#type' => 'hidden', '#value' => $app_id);
  $form['image'] = array(
    '#type' => 'file',
    '#title' => t('Select an image'),
    '#description' => t('Upload a file, allowed extensions: jpg, jpeg, png, gif'));
  $form['submit'] = array(
    '#value' => t('Submit'),
    '#type' => 'submit',
    '#name' => 'submit_image',
    '#submit' => array(
      '_application_upload_application_image_form_submit_handler'));
  return $form;
}

/**
 * Submit handler to upload an application image
 *
 * @param
 *          form
 *          The form
 *
 * @param
 *          form_state
 *          The form state
 */
function _application_upload_application_image_form_submit_handler($form, &$form_state) {
  $image = file_save_upload('image', array(
    'file_validate_is_image' => array(),  // Validates file is really an image.
    'file_validate_extensions' => array('png gif jpg jpeg'))); // Validate extensions.

  // ensure that we have a valid temp directory
  $temp = file_directory_temp();
  if (empty($temp)) {
    drupal_set_message(t('Drupal temp directory not set, file upload not possible.'), 'error');
  }
  else {
    // If the file passed validation:
    if ($image) {
      // Make sure we have the session variables set
      _ibm_apim_check_and_get_config();

      $url = '/v1/portal/orgs/' . ibm_apim_get_current_developer_org()['id'] . '/apps/' . $form_state['values']['app_id'] . '/image';
      $url = 'https://' . variable_get('ibm_apim_host') . $url;

      // curl_file_create only exists in php>=5.5
      if (function_exists('curl_file_create')) {
        $cf = curl_file_create(file_directory_temp() . '/' . drupal_basename($image->uri), $image->filemime, $image->filename);
        $data = array('file_contents' => $cf);
      }
      else {
        $filestring = '@' . file_directory_temp() . '/' . drupal_basename($image->uri) . ";filename=" . $image->filename;
        if ($image->filemime) {
          $filestring .= ';type=' . $image->filemime;
        }
        $data = array('file_contents' => $filestring);
      }
      $apim_session = &_ibm_apim_get_apim_session();
      $ch = curl_init();
      curl_setopt($ch, CURLOPT_VERBOSE, TRUE);
      curl_setopt($ch, CURLOPT_POST, TRUE);
      curl_setopt($ch, CURLOPT_HEADER, TRUE);
      curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
      curl_setopt($ch, CURLOPT_POSTFIELDS, $data);

      // Enable auto-accept of self-signed certificates if this
      // has been set in the module config by an admin.
      _ibm_apim_curl_set_accept_ssl($ch);

      curl_setopt($ch, CURLOPT_FAILONERROR, TRUE);
      curl_setopt($ch, CURLOPT_HTTPHEADER, array(
        "X-IBM-APIManagement-Context: " . $apim_session['org'] . '.' . $apim_session['env'],
        "Expect: ",
        "Authorization: Basic " . $apim_session['auth']));
      curl_setopt($ch, CURLOPT_URL, $url);
      $response = curl_exec($ch);

      if (curl_error($ch)) {
        drupal_set_message(curl_error($ch), 'error');
      }
      else {
        drupal_set_message(t('Application image updated.'));
      }

      curl_close($ch);
    }
    else {
      form_set_error('file', t('A valid file was not uploaded.'));
    }
    drupal_goto('application/' . $form_state['values']['app_id']);
  }
}

/**
 * Form to allow user to input their application secret for verification.
 *
 * @param
 *          form
 *          The form
 *
 * @param
 *          form_state
 *          The form state
 *
 * @param
 *          string appId
 *          The application ID that cooresponds to the secret
 *
 * @return array The form
 */
function _application_verify_application_secret_form($form, &$form_state, $appId) {
  $form = array();
  $form['secret'] = array(
    '#type' => 'textfield',
    '#title' => 'Secret',
    '#size' => 50,
    '#maxlength' => 50,
    '#required' => TRUE);
  $form['appid'] = array('#type' => 'hidden', '#value' => $appId);
  $form['submit'] = array('#type' => 'submit', '#value' => t('Submit'));
  $form['#submit'] = array(
    '_application_verify_application_secret_form_submit_handler');
  return $form;
}

/**
 * Form to allow user to edit their application details.
 *
 * @param
 *          form
 *          The form
 *
 * @param
 *          form_state
 *          The form state
 *
 * @param
 *          string appId
 *          The application ID to edit
 *
 * @return array The form
 */
function _application_edit_application_form($form, &$form_state, $appId) {
  $app_data = array();
  $app_data['name'] = '';
  $app_data['description'] = '';
  $app_data['oauthRedirectURI'] = '';
  $developerOrg = ibm_apim_get_current_developer_org()['id'];
  $result = _ibm_apim_call('/v1/portal/orgs/' . $developerOrg . '/apps/' . $appId);
  if (isset($result) && isset($result->data)) {
    $app_data = $result->data;
  }
  $form = array();
  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => 'Application name',
    '#size' => 25,
    '#maxlength' => 50,
    '#required' => TRUE,
    '#default_value' => $app_data['name']);
  $form['description'] = array(
    '#type' => 'textfield',
    '#title' => 'Description',
    '#size' => 100,
    '#maxlength' => 150,
    '#required' => FALSE,
    '#default_value' => $app_data['description']);
  $form['oauthurl'] = array(
    '#type' => 'textfield',
    '#title' => 'OAuth redirection URL',
    '#size' => 50,
    '#maxlength' => 100,
    '#required' => FALSE,
    '#default_value' => $app_data['oauthRedirectURI']);
  $form['developerorg'] = array('#type' => 'hidden', '#value' => $developerOrg);
  $form['appid'] = array('#type' => 'hidden', '#value' => $appId);

  $form['submit'] = array('#type' => 'submit', '#value' => t('Submit'));
  $form['#submit'] = array('_application_edit_application_form_submit_handler');
  $form['#attributes']['class'] = 'reg-form';
  return $form;
}

/**
 * Submit handler for the application edit form.
 *
 * @param
 *          form
 *          The form
 *
 * @param
 *          form_state
 *          The form state
 */
function _application_edit_application_form_submit_handler($form, &$form_state) {
  $name = $form_state['values']['name'];
  $description = $form_state['values']['description'];
  $oauthurl = $form_state['values']['oauthurl'];
  $developer_org = $form_state['values']['developerorg'];
  $app_id = $form_state['values']['appid'];

  if (empty($description)) {
    $description = '';
  }
  if (empty($oauthurl)) {
    $oauthurl = '';
  }
  // update local db
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')->entityCondition('bundle', 'application')->fieldCondition('application_apiid', 'value', $app_id);

  $results = $query->execute();

  if (isset($results['node'])) {
    $node = node_load(array_keys($results['node'])[0]);
    $node->title = $name;
    $node->application_description[$node->language][0]['value'] = $description;
    $node->application_description[$node->language][0]['safe_version'] = $description;
    $node->application_oauthredirecturi[$node->language][0]['value'] = $oauthurl;
    $node->application_oauthredirecturi[$node->language][0]['safe_version'] = $oauthurl;
    node_save($node);
  }

  // update APIm
  $url = '/v1/portal/orgs/' . $developer_org . '/apps/' . $app_id;
  $data = '{' . '"name": "' . $name . '",' . '"description": "' . $description . '",' . '"oauthRedirectURI": "' . $oauthurl . '"}';
  $result = ibm_apim_put($url, $data);
  if (isset($result) && $result->code >= 200 && $result->code < 300) {
    drupal_set_message(t('Application updated successfully.'));
    $form_state['redirect'] = 'application/' . $app_id;
  }
  else {
    $form_state['redirect'] = 'application';
  }
}

/**
 * Application secret verification form submit handler.
 *
 * @param
 *          form
 *          The form
 *
 * @param
 *          form_state
 *          The form state
 */
function _application_verify_application_secret_form_submit_handler($form, &$form_state) {
  $secret = $form_state['values']['secret'];
  $app_id = $form_state['values']['appid'];

  $url = '/v1/portal/orgs/' . ibm_apim_get_current_developer_org()['id'] . '/apps/' . $app_id . '/credentials/verify-secret';
  $data = '{"clientSecret": "' . $secret . '"}';
  $result = ibm_apim_put($url, $data);
  if (isset($result) && $result->code >= 200 && $result->code < 300) {
    drupal_set_message(t('Application secret verified successfully.'));
  }
  $form_state['redirect'] = 'application/' . $app_id;
}

/**
 * Form to allow to register a new application
 *
 * @param
 *          form
 *          The form
 *
 * @param
 *          form_state
 *          The form state
 *
 * @return array The form
 */
function _application_add_application_form($form, &$form_state) {
  $org = ibm_apim_get_current_developer_org();
  if (!isset($org)) {
    drupal_set_message(t('You must belong to a developer organization to register an application.'), 'error');
    return array();
  }

  $form = array();
  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => 'Application name',
    '#size' => 25,
    '#maxlength' => 50,
    '#required' => TRUE);
  $form['description'] = array(
    '#type' => 'textfield',
    '#title' => 'Description',
    '#size' => 100,
    '#maxlength' => 150,
    '#required' => FALSE);
  $form['oauthurl'] = array(
    '#type' => 'textfield',
    '#title' => 'OAuth redirection URL',
    '#size' => 50,
    '#maxlength' => 100,
    '#required' => FALSE);
  $form['developerorg'] = array('#type' => 'hidden', '#value' => $org['id']);

  $form['submit'] = array('#type' => 'submit', '#value' => t('Submit'));
  $form['#submit'] = array('_application_add_application_form_submit_handler');
  $form['#attributes']['class'] = 'reg-form';

  return $form;
}

/**
 * Submit handler for the add application form.
 *
 * @param
 *          form
 *          The form
 *
 * @param
 *          form_state
 *          The form state
 */
function _application_add_application_form_submit_handler($form, &$form_state) {
  $name = $form_state['values']['name'];
  $description = $form_state['values']['description'];
  $oauthurl = $form_state['values']['oauthurl'];
  $developer_org = $form_state['values']['developerorg'];

  $url = '/v1/portal/orgs/' . $developer_org . '/apps';
  $data = '{' . '"name": "' . $name . '",' . '"description": "' . $description . '",' . '"oauthRedirectURI": "' . $oauthurl . '" }';
  $result = _ibm_apim_post($url, $data);
  if (isset($result) && $result->code >= 200 && $result->code < 300) {
    drupal_set_message(t('Application created successfully.'));
    drupal_set_message(t('Your client secret is: !html_start@label!html_end', array(
      '!html_start' => '<div id="app_secret" class="appSecret"><input class="toggle-password" id="clientSecret" type="password" readonly value="' . $result->data['credentials']['clientSecret'] . '"><div class="passwordToggleContainer"><input type="checkbox" id="show-clientSecret"> <label for="show-clientSecret">',
      '@label' => t('Show Client Secret'),
      '!html_end' => '</label></div></div>')));
    $form_state['redirect'] = 'application/' . $result->data['id'];
  }
  else {
    $form_state['redirect'] = 'application/new';
  }
}

/**
 * Submit handler, just a callback, to allow user to delete an application.
 *
 * @param
 *          string appId
 *          The application ID to delete.
 */
function _application_delete_application_submit_handler($appId) {
  $developerOrg = ibm_apim_get_current_developer_org()['id'];
  $url = '/v1/portal/orgs/' . $developerOrg . '/apps/' . $appId;
  $result = _ibm_apim_delete($url);
  if (isset($result) && $result->code >= 200 && $result->code < 300) {
    // also delete the node from the drupal DB too
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'node')->entityCondition('bundle', 'application')->fieldCondition('application_apiid', 'value', $appId);
    $dbresults = $query->execute();
    if (isset($dbresults['node'])) {
      node_delete(array_keys($dbresults['node'])[0]);
    }
    drupal_set_message(t('Application deleted successfully.'));
  }
  drupal_goto('application');
}

/**
 * Submit handler, just a callback, to allow user to delete an image.
 *
 * @param
 *          string appId
 *          The application ID to delete the image from.
 */
function _application_delete_image_submit_handler($appId) {
  $developerOrg = ibm_apim_get_current_developer_org()['id'];
  $url = '/v1/portal/orgs/' . $developerOrg . '/apps/' . $appId . '/image';
  $result = _ibm_apim_delete($url);
  if (isset($result) && $result->code >= 200 && $result->code < 300) {
    drupal_set_message(t('Application image removed.'));
  }
  drupal_goto('application/' . $appId);
}

/**
 * Handler for unsubscribing an app from a plan.
 *
 * @param
 *          string appId
 *          The application ID to unsubscribe.
 * @param
 *          string subId
 *          The subscription ID to remove.
 */
function application_unsubscribeapp_submit_handler($appId = NULL, $subId = null) {
  $developerOrg = ibm_apim_get_current_developer_org()['id'];
  $url = '/v1/portal/orgs/' . $developerOrg . '/apps/' . $appId . '/subscriptions/' . $subId;
  $result = _ibm_apim_delete($url);
  if (isset($result) && $result->code >= 200 && $result->code < 300) {
    drupal_set_message(t('Application unsubscribed successfully.'));
  }
  drupal_goto('application/' . $appId);
}

/**
 * Form to select an application to register to a plan.
 *
 * @param
 *          form
 *          The form
 *
 * @param
 *          form_state
 *          The form state
 *
 * @param
 *          string planId
 *          The plan ID
 *
 * @param
 *          int @planVersion
 *          The version of the plan
 *
 * @return array The form
 */
function _application_add_application_registration_form($form, &$form_state, $planId, $planVersion) {
  $org = ibm_apim_get_current_developer_org();
  if (!isset($org)) {
    drupal_set_message(t('You must belong to a developer organization to use a plan.'), 'error');
    return array();
  }

  $app_link_info = array();
  $applist = application_list_contents();
  if ($applist) {
    foreach ($applist as $apparray) {
      $app_link_info[$apparray['orgID'] . ':' . $apparray['id']] = $apparray['name'];
    }
  }

  if (count($app_link_info) == 0) {
    drupal_set_message(t('You must register an application before selecting a plan.'), 'error');
    return array();
  }

  $form = array();
  $form['planId'] = array('#type' => 'hidden', '#value' => $planId);
  $form['planVersion'] = array('#type' => 'hidden', '#value' => $planVersion);

  $form['appId'] = array(
    '#type' => 'select',
    '#title' => 'Application',
    '#required' => TRUE,
    '#options' => $app_link_info);

  $form['submit'] = array('#type' => 'submit', '#value' => t('Use this plan'));
  $form['#submit'] = array(
    '_application_add_application_registration_form_submit_handler');
  return $form;
}

/**
 * Submit handler for the application/plan registration form.
 *
 * @param
 *          form
 *          The form
 *
 * @param
 *          form_state
 *          The form state
 */
function _application_add_application_registration_form_submit_handler($form, &$form_state) {
  list($orgId, $appId) = explode(':', $form_state['values']['appId']);
  $planId = $form_state['values']['planId'];
  $planVersion = $form_state['values']['planVersion'];

  $apim_session = &_ibm_apim_get_apim_session();
  $url = '/v1/portal/orgs/' . $apim_session['org'] . '/apps/' . $appId . '/subscriptions';
  $planurl = 'https://' . variable_get('ibm_apim_host') . '/v1/portal/plans/' . $planId . '/v' . $planVersion;
  $data = '{"planURL":" ' . $planurl . '"}';

  $result = _ibm_apim_post($url, $data);
  $form_state['redirect'] = 'plan/' . $planId . '/' . $planVersion;
}

/**
 * Form to allow user to edit their application notification settings.
 *
 * @param
 *          form
 *          The form
 *
 * @param
 *          form_state
 *          The form state
 *
 * @param
 *          string appId
 *          The application ID to edit
 *
 * @return array The form
 */
function _application_update_notification_settings_form($form, &$form_state, $appID) {
  $app_data = array();
  $app_data['enabled'] = false;
  $app_data['interval'] = 'minute';
  $app_data['emailEnabled'] = false;
  $limitdefault = 1;
  $appURL = null;
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')->entityCondition('bundle', 'application')->fieldCondition('application_apiid', 'value', $appID);
  $results = $query->execute();

  if (isset($results['node'])) {
    $node = node_load(array_keys($results['node'])[0]);
    $appURL = $node->application_url[$node->language][0]['safe_value'];
    $result = ibm_apim_get_app_notification_settings($node->application_apiid[$node->language][0]['safe_value']);
  }

  if (isset($result)) {
    $app_data = $result;
    if ($app_data['events']) {
      $limitdefault = strval(count($app_data['events']));
    }
  }
  drupal_add_js('jQuery(document).ready(function(){
    jQuery("#edit-enabled").click(function() {
        var cb1 = jQuery("#edit-enabled").is(":checked");
        jQuery("#edit-limit-1, #edit-limit-2, #edit-limit-3, #edit-limit-4").prop("disabled", !cb1);
        jQuery("#edit-interval-minute, #edit-interval-hour, #edit-interval-day").prop("disabled", !cb1);
        jQuery("#edit-emailenabled").prop("disabled", !cb1);
    });
        });', 'inline');

  $default = !$app_data['enabled'];
  $form = array();
  $form['enabled'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable notifications for this application'),
    '#default_value' => $app_data['enabled'],
    '#weight' => 0);
  $form['notify_fieldset'] = array(
    '#type' => 'fieldset',
    '#weight' => 2,
    '#title' => t('Send a notification when'));
  // the options to display in our form radio buttons
  $options = array(
    '1' => t('Rate limit is exceeded'),
    '2' => t('90% of the Rate limit is reached'),
    '3' => t('75% of the Rate limit is reached'),
    '4' => t('50% of the Rate limit is reached'));
  $form['notify_fieldset']['limit'] = array(
    '#type' => 'radios',
    '#weight' => 6,
    '#disabled' => $default,
    '#options' => $options,
    '#required' => true,
    '#default_value' => $limitdefault);

  $values = array(
    'minute' => t('Every minute'),
    'hour' => t('Every hour'),
    'day' => t('Every day'));
  $form['notify_fieldset']['interval'] = array(
    '#type' => 'radios',
    '#weight' => 7,
    '#disabled' => $default,
    '#title' => "Select how often to send notifications",
    '#options' => $values,
    '#default_value' => $app_data['interval']);

  $form['activityFeed'] = array(
    '#type' => 'checkbox',
    '#disabled' => TRUE,
    '#title' => t('Built-in activity feed'),
    '#default_value' => true,
    '#weight' => 8);
  $form['emailEnabled'] = array(
    '#type' => 'checkbox',
    '#disabled' => $default,
    '#title' => t('Email'),
    '#default_value' => $app_data['emailEnabled'],
    '#weight' => 9);

  $form['appurl'] = array('#type' => 'hidden', '#value' => $appURL);

  $form['submit'] = array(
    '#type' => 'submit',
    '#weight' => 10,
    '#value' => t('Submit'));
  $form['#submit'] = array(
    '_application_update_notification_settings_form_submit_handler');
  $form['#attributes']['class'] = 'reg-form appNotificationSettings';
  return $form;
}

/* This seems to be the only way to have a checkbox field that's disabled */
function _application_update_notification_settings_form_alter(&$form, &$form_state, $form_id) {
  $form['activityFeed']['#disabled'] = TRUE; // disables activityFeed checkbox
}

/**
 * Submit handler for the application notification settings form.
 *
 * @param
 *          form
 *          The form
 *
 * @param
 *          form_state
 *          The form state
 */
function _application_update_notification_settings_form_submit_handler($form, &$form_state) {
  $enabled = $form_state['values']['enabled'];
  $emailEnabled = $form_state['values']['emailEnabled'];
  $interval = $form_state['values']['interval'];
  $limit = $form_state['values']['limit'];
  $appURL = $form_state['values']['appurl'];

  $settings = array();
  $settings['appURL'] = $appURL;
  $settings['enabled'] = $enabled;
  $settings['emailEnabled'] = $emailEnabled;
  $settings['interval'] = $interval;
  $settings['events'] = array();
  switch ($limit) {
    case '1' :
      $settings['events'][] = "rateLimitPercent100";
      break;
    case '2' :
      $settings['events'][] = "rateLimitPercent90";
      $settings['events'][] = "rateLimitPercent100";
      break;
    case '3' :
      $settings['events'][] = "rateLimitPercent75";
      $settings['events'][] = "rateLimitPercent90";
      $settings['events'][] = "rateLimitPercent100";
      break;
    case '4' :
      $settings['events'][] = "rateLimitPercent50";
      $settings['events'][] = "rateLimitPercent75";
      $settings['events'][] = "rateLimitPercent90";
      $settings['events'][] = "rateLimitPercent100";
      break;
  }

  // update APIm
  $result = ibm_apim_update_user_settings($appURL, $settings);
  if (isset($result) && $result->code >= 200 && $result->code < 300) {
    drupal_set_message(t('Notification settings updated successfully.'));
    $form_state['redirect'] = 'application/' . $app_id;
  }
  else {
    $form_state['redirect'] = 'application';
  }
}

/**
 * Form to list the current user's applications in a select box.
 *
 * @return array An array of applications, with the ID as the key and name as value.
 */
function _application_app_select_options() {
  $app_details = application_list_contents();
  if (!isset($app_details)) {
    return NULL;
  }
  $app_array = array();
  $app_array[''] = 'Select an application';
  foreach ($app_details as $app_detail) {
    $app_array[$app_detail['id']] = $app_detail['name'];
  }
  return $app_array;
}

/**
 * Function to introspect the plan URL and return the ID and version
 *
 * @return array An array with id and version.
 */
function _application_get_id_and_ver_from_planurl($planurl) {
  $parts = parse_url($planurl);
  if ($parts) {
    $planpath = $parts['path'];
    $dirs = explode('/', $planpath);
    $version = array_pop($dirs);
    $version = ltrim($version, 'v');
    $id = array_pop($dirs);
    $ret = array('id' => $id, 'version' => $version);
  }
  return $ret;
}